os: linux

services:
    - docker
sudo: required
language: python
env:
    global:
        - CONAN_UPLOAD=1
        - CONAN_REFERENCE=extra-cmake-modules/5.29.0
        - CONAN_USERNAME=russelltg
        - CONAN_CHANNEL=stable
        - CONAN_USE_DOCKER=1  
        - CONAN_GCC_VERSIONS=6.2
        # password in in travis settings

install:
  - ./.travis/install.sh
script:
  - ./.travis/run.sh
